// pages/TemplateUsage.jsx
import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { 
  FileText, Download, Loader2, ArrowLeft, 
  Eye, Printer, CloudUpload, Sparkles,
  CheckCircle, AlertCircle, Zap, Shield, Clock
} from 'lucide-react';

export default function TemplateUsage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [template, setTemplate] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [formData, setFormData] = useState({});
  const [previewMode, setPreviewMode] = useState(false);
  const [uploadToDrive, setUploadToDrive] = useState(false);
  const [driveStatus, setDriveStatus] = useState(null);
  const printRef = useRef(null);

  useEffect(() => {
    fetchTemplate();
  }, [id]);

  const fetchTemplate = async () => {
    try {
      const token = localStorage.getItem('token');
      const res = await axios.get(`http://localhost:5000/api/templates/${id}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      setTemplate(res.data);
      
      // Initialize form data with default values
      const initialData = {};
      res.data.fields.forEach(field => {
        initialData[field.id] = field.defaultValue || '';
      });
      setFormData(initialData);
    } catch (err) {
      console.error('Fetch template error:', err);
      alert('Failed to load template');
      navigate('/templates');
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (fieldId, value) => {
    setFormData({ ...formData, [fieldId]: value });
  };

  const handlePrint = () => {
    // Create a printable version of the form data
    const printWindow = window.open('', '_blank');
    const fieldsHtml = template.fields.map(field => `
      <div style="margin-bottom: 15px; padding: 10px; border-bottom: 1px solid #e2e8f0;">
        <strong style="color: #4f46e5; font-size: 12px; text-transform: uppercase;">${field.label}</strong>
        <p style="margin-top: 5px; color: #334155;">${formData[field.id] || 'Not provided'}</p>
      </div>
    `).join('');
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${template.name} - Print</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: Arial, sans-serif; padding: 40px; background: white; }
          .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 2px solid #4f46e5; }
          .header h1 { color: #1e293b; font-size: 24px; margin-bottom: 5px; }
          .header p { color: #64748b; font-size: 12px; }
          .content { max-width: 800px; margin: 0 auto; }
          .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }
          @media print {
            body { padding: 20px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="content">
          <div class="header">
            <h1>${template.name}</h1>
            <p>Generated on ${new Date().toLocaleString()}</p>
            <p>Document ID: #${Date.now().toString().slice(-8)}</p>
          </div>
          <div class="fields">
            ${fieldsHtml}
          </div>
          <div class="footer">
            <p>Generated by DocuGen - Professional Document Solutions</p>
            <p>This is a computer-generated document. Valid without signature.</p>
          </div>
        </div>
        <script>
          window.onload = () => { window.print(); setTimeout(() => window.close(), 500); };
        </script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  const generateDocument = async () => {
    // Validate required fields
    const missingFields = template.fields.filter(field => 
      field.required && !formData[field.id]
    );
    
    if (missingFields.length > 0) {
      alert(`Please fill in required fields: ${missingFields.map(f => f.label).join(', ')}`);
      return;
    }
    
    setGenerating(true);
    setDriveStatus(null);
    
    try {
      const token = localStorage.getItem('token');
      const res = await axios.post(
        `http://localhost:5000/api/templates/${id}/generate`,
        { data: formData, uploadToDrive },
        {
          responseType: 'blob',
          headers: { Authorization: `Bearer ${token}` }
        }
      );
      
      // Download the generated PDF
      const url = window.URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }));
      const link = document.createElement('a');
      link.href = url;
      link.download = `${template.name}_${Date.now()}.pdf`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
      
      // Check if uploaded to Drive from response headers
      const uploadedToDrive = res.headers['x-drive-uploaded'];
      if (uploadedToDrive === 'true') {
        setDriveStatus('success');
        setTimeout(() => setDriveStatus(null), 5000);
      } else if (uploadToDrive && uploadedToDrive === 'false') {
        setDriveStatus('error');
        setTimeout(() => setDriveStatus(null), 5000);
      }
      
      alert('Document generated successfully!');
    } catch (err) {
      console.error('Generate error:', err);
      alert('Failed to generate document');
    } finally {
      setGenerating(false);
    }
  };

  const getInputComponent = (field) => {
    const value = formData[field.id] || '';
    const style = field.style || {};

    const inputStyle = {
      fontSize: style.fontSize,
      color: style.fontColor,
      fontWeight: style.fontWeight,
      textAlign: style.textAlign
    };

    switch (field.type) {
      case 'textarea':
        return (
          <textarea
            placeholder={field.placeholder}
            value={value}
            onChange={(e) => handleInputChange(field.id, e.target.value)}
            className="w-full px-4 py-2.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition"
            rows={4}
            style={inputStyle}
          />
        );
      case 'currency':
        return (
          <div className="relative">
            <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">₹</span>
            <input
              type="number"
              placeholder={field.placeholder}
              value={value}
              onChange={(e) => handleInputChange(field.id, e.target.value)}
              className="w-full pl-8 pr-4 py-2.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition"
              style={inputStyle}
            />
          </div>
        );
      case 'date':
        return (
          <input
            type="date"
            value={value}
            onChange={(e) => handleInputChange(field.id, e.target.value)}
            className="w-full px-4 py-2.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition"
            style={inputStyle}
          />
        );
      case 'signature':
        return (
          <div className="border-2 border-dashed border-slate-200 rounded-xl p-4 text-center hover:border-indigo-300 transition">
            <p className="text-sm text-slate-400 mb-2">✍️ Click to add signature</p>
            <input
              type="text"
              placeholder="Type your name to sign"
              value={value}
              onChange={(e) => handleInputChange(field.id, e.target.value)}
              className="w-full px-4 py-2 border border-slate-200 rounded-lg focus:ring-2 focus:ring-indigo-500"
            />
          </div>
        );
      default:
        return (
          <input
            type={field.type === 'number' ? 'number' : 'text'}
            placeholder={field.placeholder}
            value={value}
            onChange={(e) => handleInputChange(field.id, e.target.value)}
            className="w-full px-4 py-2.5 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition"
            style={inputStyle}
          />
        );
    }
  };

  // Calculate progress percentage
  const filledFields = template?.fields.filter(field => formData[field.id]).length || 0;
  const totalFields = template?.fields.length || 0;
  const progress = totalFields > 0 ? (filledFields / totalFields) * 100 : 0;

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="relative">
          <div className="animate-spin rounded-full h-16 w-16 border-4 border-indigo-200 border-t-indigo-600"></div>
          <div className="absolute inset-0 flex items-center justify-center">
            <Sparkles className="text-indigo-400 animate-pulse" size={24} />
          </div>
        </div>
      </div>
    );
  }

  if (!template) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="text-center bg-white rounded-2xl p-8 shadow-sm border border-slate-200 max-w-md mx-4">
          <div className="w-20 h-20 bg-slate-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <FileText size={40} className="text-slate-300" />
          </div>
          <p className="text-slate-500 font-medium">Template not found</p>
          <button
            onClick={() => navigate('/templates')}
            className="mt-4 text-indigo-600 hover:underline"
          >
            Back to Templates
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-6 sm:py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-6 sm:mb-8">
          <button
            onClick={() => navigate('/templates')}
            className="flex items-center gap-2 text-slate-500 hover:text-slate-700 transition group"
          >
            <ArrowLeft size={18} className="group-hover:-translate-x-1 transition" />
            <span className="hidden sm:inline">Back to Templates</span>
          </button>
          
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-100 rounded-lg flex items-center justify-center">
              <FileText size={16} className="text-indigo-600" />
            </div>
            <span className="text-sm font-medium text-slate-600">Template Usage</span>
          </div>
        </div>

        {/* Template Info Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-5 sm:p-6 mb-6">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div>
              <h1 className="text-xl sm:text-2xl font-bold text-slate-800">{template.name}</h1>
              <p className="text-slate-500 text-sm mt-1">{template.description}</p>
            </div>
            <div className="flex items-center gap-2">
              <span className="text-xs px-2.5 py-1 rounded-full bg-indigo-100 text-indigo-700 whitespace-nowrap">
                {template.category}
              </span>
              {template.isPublic && (
                <span className="text-xs px-2.5 py-1 rounded-full bg-green-100 text-green-700 whitespace-nowrap">
                  Public
                </span>
              )}
            </div>
          </div>
          
          {/* Progress Bar */}
          <div className="mt-4 pt-3 border-t border-slate-100">
            <div className="flex justify-between text-xs text-slate-500 mb-1.5">
              <span>Completion Progress</span>
              <span>{filledFields}/{totalFields} fields filled</span>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-2 overflow-hidden">
              <div 
                className="bg-gradient-to-r from-indigo-500 to-violet-500 h-2 rounded-full transition-all duration-500"
                style={{ width: `${progress}%` }}
              />
            </div>
          </div>
        </div>

        {/* Form Fields Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
          <div className="bg-gradient-to-r from-indigo-600 to-violet-600 px-5 sm:px-6 py-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-white/20 rounded-xl flex items-center justify-center">
                  <Sparkles size={20} className="text-white" />
                </div>
                <div>
                  <h2 className="text-white font-semibold">Fill in the Details</h2>
                  <p className="text-indigo-100 text-xs">Complete the form to generate your document</p>
                </div>
              </div>
              <button
                onClick={() => setPreviewMode(!previewMode)}
                className="flex items-center justify-center gap-2 px-3 py-1.5 bg-white/10 rounded-lg text-sm text-white hover:bg-white/20 transition"
              >
                <Eye size={14} />
                {previewMode ? 'Edit Mode' : 'Preview'}
              </button>
            </div>
          </div>
          
          <div className="p-5 sm:p-6">
            {previewMode ? (
              <div className="space-y-4">
                {template.fields.map((field) => (
                  <div key={field.id} className="bg-slate-50 rounded-xl p-4 border border-slate-100">
                    <p className="text-xs font-medium text-slate-500 mb-1">{field.label}</p>
                    <p className="text-slate-700 break-words">
                      {formData[field.id] ? (
                        <span className="flex items-center gap-2">
                          <CheckCircle size={14} className="text-green-500" />
                          {formData[field.id]}
                        </span>
                      ) : (
                        <span className="text-slate-400 italic flex items-center gap-2">
                          <AlertCircle size={14} />
                          Not filled
                        </span>
                      )}
                    </p>
                  </div>
                ))}
              </div>
            ) : (
              <div className="space-y-5">
                {template.fields.map((field) => (
                  <div key={field.id}>
                    <label className="block text-sm font-semibold text-slate-700 mb-1.5">
                      {field.label} {field.required && <span className="text-red-500">*</span>}
                    </label>
                    {getInputComponent(field)}
                  </div>
                ))}
              </div>
            )}
            
            {/* Google Drive Option */}
            {!previewMode && (
              <div className="mt-6 p-3 bg-slate-50 rounded-xl border border-slate-100">
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    checked={uploadToDrive}
                    onChange={(e) => setUploadToDrive(e.target.checked)}
                    id="upload-drive"
                    className="w-4 h-4 rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                  />
                  <label htmlFor="upload-drive" className="flex items-center gap-2 cursor-pointer">
                    <CloudUpload size={16} className="text-indigo-600" />
                    <div>
                      <span className="text-sm font-medium text-slate-700">Save to Google Drive</span>
                      <p className="text-xs text-slate-400">Automatically upload generated document to Drive</p>
                    </div>
                  </label>
                </div>
                
                {driveStatus === 'success' && (
                  <div className="mt-3 p-2.5 bg-green-50 rounded-lg flex items-center gap-2">
                    <CheckCircle size={14} className="text-green-600" />
                    <span className="text-sm text-green-700">Document saved to Google Drive!</span>
                  </div>
                )}
                
                {driveStatus === 'error' && (
                  <div className="mt-3 p-2.5 bg-red-50 rounded-lg flex items-center gap-2">
                    <AlertCircle size={14} className="text-red-600" />
                    <span className="text-sm text-red-700">Failed to save to Drive. Please check connection.</span>
                  </div>
                )}
              </div>
            )}
            
            {/* Action Buttons */}
            <div className={`mt-6 flex gap-3 ${previewMode ? 'pt-6 border-t border-slate-100' : ''}`}>
              <button
                onClick={generateDocument}
                disabled={generating}
                className="flex-1 bg-gradient-to-r from-indigo-600 to-violet-600 text-white py-3 rounded-xl font-semibold flex items-center justify-center gap-2 hover:shadow-lg hover:scale-[1.02] transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {generating ? (
                  <>
                    <Loader2 size={18} className="animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Download size={18} />
                    Generate Document
                  </>
                )}
              </button>
              
              {!previewMode && (
                <button 
                  onClick={handlePrint}
                  className="px-4 py-3 border border-slate-200 rounded-xl text-slate-600 hover:bg-slate-50 transition"
                  title="Print Preview"
                >
                  <Printer size={18} />
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Features Banner */}
        <div className="mt-8 grid grid-cols-2 sm:grid-cols-4 gap-3">
          <div className="bg-white rounded-xl p-3 shadow-sm border border-slate-100 flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-50 rounded-lg flex items-center justify-center">
              <Zap size={14} className="text-indigo-600" />
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-700">Fast Generation</p>
              <p className="text-[10px] text-slate-400">Instant PDF</p>
            </div>
          </div>
          <div className="bg-white rounded-xl p-3 shadow-sm border border-slate-100 flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-50 rounded-lg flex items-center justify-center">
              <Shield size={14} className="text-indigo-600" />
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-700">Secure</p>
              <p className="text-[10px] text-slate-400">Encrypted</p>
            </div>
          </div>
          <div className="bg-white rounded-xl p-3 shadow-sm border border-slate-100 flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-50 rounded-lg flex items-center justify-center">
              <CloudUpload size={14} className="text-indigo-600" />
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-700">Cloud Backup</p>
              <p className="text-[10px] text-slate-400">Drive Support</p>
            </div>
          </div>
          <div className="bg-white rounded-xl p-3 shadow-sm border border-slate-100 flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-50 rounded-lg flex items-center justify-center">
              <Clock size={14} className="text-indigo-600" />
            </div>
            <div>
              <p className="text-xs font-semibold text-slate-700">Quick Save</p>
              <p className="text-[10px] text-slate-400">Auto Download</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}